name: Production-Deployment

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: checkout code
      
    - name: Build the Docker image
      run: docker build -t subx1900/echo:${{ github.sha }} .
    
    - name: Push the Docker image
      run: echo '${{ secrets.DOCKER_PASS }}' | docker login --username '${{ secrets.DOCKER_USER }}' --password-stdin && docker push subx1900/echo:${{ github.sha }}

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'echo'
        namespace: 'platform-stage'
        chart: 'echo-chart'
        helm: 'helm3'  
        token: '${{ github.token }}'
        values: |
          replicaCount: 2
          image:
            repository: subx1900/echo
            tag: ${{ github.sha }}
            honeybadgerApiKey: ${{ secrets.HONEYBADGER_API_KEY }}
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
